#!/bin/bash

# $1 = funjoy  项目名
# $2 = Debug  模式
# $3 = u1   环境名

targetName=$1
projectHome=`pwd`
configuration=$2
#env=$3

currentTime=`date '+%Y-%m-%d-%H-%M'`

#auto increase build no
# plist文件所在路径
buildPlist=$projectHome/$targetName/Info.plist
echo $buildPlist
plistBuddy=/usr/libexec/PlistBuddy
CFBundleVersion=$($plistBuddy -c "Print CFBundleVersion" $buildPlist)
CFBundleVersion=$(($CFBundleVersion+1))
$plistBuddy -c "Set :CFBundleVersion $CFBundleVersion" $buildPlist

#build文件夹路径
build_path=$projectHome/build

#定义ipa文件的路径
ipaFilePath=$projectHome/target/"$targetName"_build_"$CFBundleVersion"

#清理环境
xcodebuild clean -configuration $configuration #clean project
rm -rf target/*.ipa
rm -rf build/$configuration-iphoneos/*.app

xcodebuild clean \
-scheme ${targetName} \
-configuration ${configuration}

echo '///--------'  
echo '/// 清理完成'  
echo '///--------'  
echo ''


#更新plist中的属性值
# ./update_plist $targetName product
#编译并打包ipa文件
xcodebuild archive \
-workspace ${targetName}.xcworkspace \
-scheme ${targetName} \
-archivePath ${build_path}/${targetName}.xcarchive -quiet  || exit 

echo '///--------'  
echo '/// 编译完成'  
echo '///--------'  
echo ''


# 导出ipa包
xcodebuild -exportArchive \
-archivePath "${build_path}/${targetName}.xcarchive" \
-exportPath ${ipaFilePath} \
-exportOptionsPlist ${buildPlist} \
-quiet || exit

if [ -e $ipaFilePath/$targetName.ipa ];  
    then  
    echo '///----------'  
    echo '/// ipa包已导出'  
    echo '///----------'  
    open $ipaFilePath  
    else  
    echo '///-------------'  
    echo '/// ipa包导出失败 '  
    echo '///-------------'  
fi  
echo '///------------'  
echo '/// 打包ipa完成  '  
echo '///-----------='  
echo ''
